extends SceneTree
## Mirrors NTSCRT Tests/CrtCoreTests/PreviewScalingTests.swift.
const Scaler = preload("res://addons/ntscrt/internal/ntscrt_preview_scaler.gd")
const INPUTS = [Vector2i(320,320),Vector2i(320,240),Vector2i(256,224)]
const DRAWABLES = [Vector2i(632,632),Vector2i(900,700),Vector2i(1132,1132),Vector2i(1346,1346),Vector2i(1532,1532),Vector2i(2000,1400),Vector2i(2560,1600),Vector2i(3000,2200)]
var checks = 0
var failures: Array[String] = []
func check(ok: bool, label: String) -> void:
	checks += 1
	if not ok: failures.append(label); push_error(label)
func _initialize() -> void:
	for input in INPUTS:
		for drawable in DRAWABLES:
			var p = Scaler.plan(input,drawable,true)
			if p.display_multiple>0:
				check(p.display_size==input*p.display_multiple,"display is whole input multiple")
				check(p.render_multiple%p.display_multiple==0,"render is whole display multiple")
				check(p.render_size.x%p.display_size.x==0 and p.render_size.y%p.display_size.y==0,"integer box-downsample ratios")
			check(p.display_size.x<=drawable.x and p.display_size.y<=drawable.y,"display fits drawable")
	var seen = {}
	for width in range(700,2601,7):
		var p = Scaler.plan(Vector2i(320,320),Vector2i(width,width),true)
		seen[p.display_size.x] = true
		check(p.display_size.x%320==0,"display steps on 320-pixel grid")
	check(seen.size()<=8,"growing window takes few discrete display sizes")
	var on = Scaler.plan(Vector2i(320,320),Vector2i(1346,1346),true)
	var off = Scaler.plan(Vector2i(320,320),Vector2i(1346,1346),false)
	check(on.display_size==Vector2i(1280,1280) and off.display_size==Vector2i(1346,1346),"integer toggle visibly changes magnification")
	for drawable in DRAWABLES:
		var on_plan = Scaler.plan(Vector2i(320,320),drawable,true)
		check(on_plan.render_multiple>=6,"scanline floor at every fixture window")
		var off_plan = Scaler.plan(Vector2i(320,320),drawable,false)
		check(off_plan.display_size==drawable,"noninteger fills drawable")
		check(off_plan.render_multiple>=6 and off_plan.render_multiple%2==0,"noninteger render is even with scanline floor")
		check(off_plan.render_size==Vector2i(320,320)*off_plan.render_multiple and off_plan.needs_downsample,"noninteger render is independently sized and downsampled")
	for input in [Vector2i(320,320),Vector2i(1024,1024),Vector2i(1920,1080),Vector2i(3840,2160)]:
		for drawable in DRAWABLES:
			var p = Scaler.plan(input,drawable,true,6,4096)
			check(maxi(p.render_size.x,p.render_size.y)<=4096,"original budget fixtures stay within cap")
	check(Scaler.plan(Vector2i(320,320),Vector2i(1600,1600),true).display_multiple==4,"odd five-times display snaps to four")
	var tiny = Scaler.plan(Vector2i(320,320),Vector2i(200,200),true)
	check(tiny.display_multiple==0 and tiny.display_size==Vector2i(200,200) and tiny.render_multiple>=6,"tiny window fits while rendering retains scanlines")
	# Exact additional goldens generated by unmodified upstream Swift.
	var fixtures = [
		[Vector2i(320,240),Vector2i(200,100),true,6,4096,Vector2i(1920,1440),Vector2i(133,100),0,6],
		[Vector2i(1024,1024),Vector2i(2000,1400),false,6,4096,Vector2i(4096,4096),Vector2i(2000,1400),0,4],
		[Vector2i(0,320),Vector2i(9000,100),true,6,4096,Vector2i(4096,64),Vector2i(9000,100),0,0],
		[Vector2i(5000,3000),Vector2i(900,700),false,6,4096,Vector2i(900,700),Vector2i(900,700),0,0],
		[Vector2i(5000,3000),Vector2i(900,700),true,6,4096,Vector2i(5000,3000),Vector2i(900,540),0,1],
		[Vector2i(320,240),Vector2i(6000,4500),true,6,4096,Vector2i(5760,4320),Vector2i(5760,4320),18,18],
		[Vector2i(320,240),Vector2i(960,720),false,5,4096,Vector2i(1280,960),Vector2i(960,720),0,4],
		[Vector2i(320,240),Vector2i(-1,0),true,6,4096,Vector2i(1920,1440),Vector2i(1,1),0,6],
	]
	for f in fixtures:
		var p = Scaler.plan(f[0],f[1],f[2],f[3],f[4])
		check(p.render_size==f[5] and p.display_size==f[6] and p.display_multiple==f[7] and p.render_multiple==f[8],"Swift sizing golden: "+str(f))
	print("PREVIEW_SCALER_AUDIT ","PASS" if failures.is_empty() else "FAIL"," checks=",checks," failures=",failures)
	quit(0 if failures.is_empty() else 1)
