extends RefCounted
## Original authored looks. Camera entries describe a digitized AV output, not
## a DV codec, exact camera model, frame-rate conversion or infrared lighting.
const PROFILE = preload("res://addons/ntscrt/profile.gd")
const IO = preload("res://addons/ntscrt/preset_io.gd")
const CAMERA := {
	"use_field":3,"filter_type":1,"input_luma_filter":2,"chroma_lowpass_in":1,
	"composite_preemphasis":0.18,"composite_noise":true,"composite_noise_intensity":0.002,
	"snow_intensity":0.0,"chroma_demodulation":3,"luma_smear":0.02,
	"head_switching":false,"tracking_noise":false,"ringing":false,
	"luma_noise":true,"luma_noise_intensity":0.001,
	"chroma_noise":true,"chroma_noise_intensity":0.006,"chroma_noise_detail":1,
	"chroma_phase_error":0.0,"chroma_phase_noise_intensity":0.0001,
	"chroma_delay_horizontal":0.0,"chroma_delay_vertical":0,
	"vhs_settings":false,"vhs_tape_speed":0,"vhs_chroma_loss":0.0,
	"vhs_edge_wave_enabled":false,"vhs_sharpen_enabled":false,
	"chroma_lowpass_out":1,"scale_with_video_size":true,
}
const VHS := {
	"filter_type":0,"chroma_lowpass_in":2,"chroma_lowpass_out":2,
	"chroma_demodulation":1,"luma_smear":0.12,"composite_preemphasis":0.25,
	"composite_noise_intensity":0.006,"luma_noise_intensity":0.002,
	"chroma_noise_intensity":0.025,"chroma_phase_noise_intensity":0.0004,
	"head_switching":true,"head_switching_height":4,"head_switching_offset":3,
	"head_switching_horizontal_shift":8.0,"head_switching_start_mid_line":false,
	"vhs_settings":true,"vhs_tape_speed":1,"vhs_chroma_loss":0.000002,
	"vhs_sharpen_enabled":true,"vhs_sharpen":0.15,
	"vhs_edge_wave_enabled":true,"vhs_edge_wave":0.12,"vhs_edge_wave_speed":1.4,
}
# Compact authoring recipes become COMPLETE profiles before use or export.
# Tape wear is fixed at .5 so these signal amplitudes are applied exactly once.
const LOOKS := [
	{"id":"clean",
	 "name":"Clean reference",
	 "group":"Reference",
	 "description":"Unfiltered picture. Compare brightness and detail against any recording look.",
	 "route":"No tape processing · no CRT",
	 "tape":0,
	 "grain":0.0},
	{"id":"minidv-day",
	 "name":"MiniDV · daylight",
	 "group":"Camera capture",
	 "description":"A well-kept digital camcorder captured through its AV cable: crisp edges, restrained color bleed and almost no noise.",
	 "route":"AV capture · no VHS wear · no CRT",
	 "grain":0.025,
	 "saturation":1.03,
	 "temperature":-0.08,
	 "signal":{"composite_preemphasis":0.32,"chroma_noise_intensity":0.003}},
	{"id":"minidv-night",
	 "name":"MiniDV · low light",
	 "group":"Camera capture",
	 "description":"A camcorder struggling after dark: visible gain noise, cooler white balance and muted colors. No VHS tracking damage.",
	 "route":"AV capture · no VHS wear · no CRT",
	 "grain":0.4,
	 "saturation":0.72,
	 "temperature":-0.18,
	 "lift":0.025,
	 "signal":{"luma_noise_intensity":0.14,"chroma_noise_intensity":0.1,"composite_preemphasis":0.3,"composite_noise_intensity":0.008}},
	{"id":"hi8",
	 "name":"Hi8 · family camcorder",
	 "group":"Camera capture",
	 "description":"Fairly sharp luma with softer color edges and a little sensor noise. A clean first-generation home recording.",
	 "route":"Analog camera capture · no CRT",
	 "grain":0.12,
	 "saturation":1.08,
	 "temperature":0.16,
	 "signal":{"chroma_lowpass_in":2,"chroma_lowpass_out":2,"luma_smear":0.065,"chroma_noise_intensity":0.035,"chroma_delay_horizontal":0.35,"composite_preemphasis":0.4,"luma_noise_intensity":0.012,"composite_noise_intensity":0.01,"bandwidth_scale":1.1}},
	{"id":"video8",
	 "name":"Video8 · worn handheld",
	 "group":"Camera capture",
	 "description":"A worn handheld recording: rougher color, restless edges and occasional small dropouts. Sharper than a heavily copied VHS tape.",
	 "route":"Analog camera capture · no CRT",
	 "grain":0.2,
	 "saturation":0.8,
	 "temperature":0.2,
	 "lift":0.02,
	 "signal":{"filter_type":0,"chroma_lowpass_in":2,"chroma_lowpass_out":2,"luma_smear":0.16,"chroma_noise_intensity":0.075,"composite_noise_intensity":0.025,"chroma_delay_horizontal":0.7,"luma_noise_intensity":0.025,"vhs_settings":true,"vhs_tape_speed":0,"vhs_edge_wave_enabled":true,"vhs_edge_wave":0.55,"vhs_edge_wave_speed":2.0,"chroma_phase_noise_intensity":0.003},
	 "fault_rate":2.0,
	 "fault_strength":0.3},
	{"id":"vhs-c",
	 "name":"VHS-C · family holiday",
	 "group":"VHS capture",
	 "description":"Warm, colorful home movies: soft bleeding reds, mild tape hiss and a visible narrow switching line at the bottom. A fresh-tape look.",
	 "route":"VHS SP capture · no CRT",
	 "vhs":true,
	 "grain":0.15,
	 "saturation":1.12,
	 "temperature":0.5,
	 "signal":{"luma_smear":0.1,"vhs_edge_wave":0.08,"chroma_noise_intensity":0.07,"composite_noise_intensity":0.014,"luma_noise_intensity":0.012,"chroma_delay_horizontal":1.3,"head_switching_height":6,"head_switching_offset":2}},
	{"id":"vhs-shoulder",
	 "name":"VHS · shoulder camera",
	 "group":"VHS capture",
	 "description":"An older full-size camera: warm, slightly faded color, electronic edge halos and a textured tape signal. More brittle than the holiday camcorder.",
	 "route":"VHS SP capture · no CRT",
	 "vhs":true,
	 "grain":0.18,
	 "saturation":0.82,
	 "temperature":0.4,
	 "signal":{"filter_type":1,"vhs_sharpen":0.65,"luma_smear":0.07,"chroma_delay_horizontal":0.5,"luma_noise_intensity":0.025,"composite_noise_intensity":0.024,"chroma_noise_intensity":0.09,"vhs_edge_wave":0.3,"ringing":true,"ringing_power":3.0,"ringing_scale":0.12,"chroma_phase_noise_intensity":0.004}},
	{"id":"vhs-lp",
	 "name":"VHS · long-play recording",
	 "group":"VHS capture",
	 "description":"An extended recording on slow tape: visibly soft detail, noisy color, bottom-edge wear and occasional dropouts. A dirty everyday recording.",
	 "route":"VHS extended-play capture · no CRT",
	 "vhs":true,
	 "grain":0.25,
	 "saturation":0.84,
	 "lift":0.025,
	 "signal":{"vhs_tape_speed":3,"luma_smear":0.25,"chroma_noise_intensity":0.15,"composite_noise_intensity":0.07,"vhs_edge_wave":0.7,"chroma_delay_horizontal":2.5,"luma_noise_intensity":0.05,"head_switching_height":9,"head_switching_offset":2,"head_switching_horizontal_shift":30.0,"tracking_noise":true,"tracking_noise_height":8,"tracking_noise_noise_intensity":0.12,"tracking_noise_wave_intensity":4.0,"tracking_noise_snow_intensity":0.003,"bandwidth_scale":0.86},
	 "fault_rate":3.0,
	 "fault_strength":0.35},
	{"id":"found-original",
	 "name":"Found footage · original tape",
	 "group":"Found footage",
	 "description":"A recovered recording with visible noise, bleeding color, wavering edges and occasional brief dropouts. The main found-footage candidate.",
	 "route":"VHS capture · no CRT",
	 "vhs":true,
	 "grain":0.32,
	 "saturation":0.72,
	 "temperature":-0.1,
	 "lift":0.035,
	 "signal":{"vhs_edge_wave":0.8,"chroma_noise_intensity":0.18,"vhs_chroma_loss":0.0004,"composite_noise_intensity":0.09,"chroma_delay_horizontal":1.7,"luma_noise_intensity":0.065,"head_switching_height":9,"head_switching_offset":3,"head_switching_horizontal_shift":26.0,"tracking_noise":true,"tracking_noise_height":8,"tracking_noise_wave_intensity":4.0,"tracking_noise_noise_intensity":0.12,"tracking_noise_snow_intensity":0.003},
	 "fault_rate":4.0,
	 "fault_strength":0.4},
	{"id":"found-copy",
	 "name":"Found footage · archive copy",
	 "group":"Found footage",
	 "description":"A worn dub: coarse noise, smeared color, an unstable lower edge and brief tracking breaks. Visibly rougher than the original tape.",
	 "route":"VHS copy · no CRT",
	 "vhs":true,
	 "grain":0.4,
	 "saturation":0.58,
	 "temperature":0.12,
	 "lift":0.045,
	 "signal":{"vhs_tape_speed":3,"luma_smear":0.5,"vhs_sharpen":0.06,"chroma_noise_intensity":0.3,"chroma_delay_horizontal":3.5,"vhs_edge_wave":1.6,"vhs_chroma_loss":0.001,"tracking_noise":true,"tracking_noise_height":18,"tracking_noise_wave_intensity":12.0,"tracking_noise_snow_intensity":0.012,"tracking_noise_noise_intensity":0.22,"composite_noise_intensity":0.17,"luma_noise_intensity":0.11,"snow_intensity":0.006,"head_switching_height":12,"head_switching_offset":3,"head_switching_horizontal_shift":42.0},
	 "fault_rate":8.0,
	 "fault_strength":0.7,
	 "fault_kind":0},
	{"id":"cctv-color",
	 "name":"Security camera · color",
	 "group":"Surveillance",
	 "description":"Cheap color surveillance: lower detail, a cool washed-out palette and constant electronic noise. No tape wobble or tracking breaks.",
	 "route":"Live analog feed · no CRT",
	 "grain":0.22,
	 "saturation":0.56,
	 "temperature":-0.3,
	 "lift":0.023,
	 "signal":{"input_luma_filter":1,"filter_type":0,"luma_smear":0.13,"chroma_lowpass_in":2,"chroma_lowpass_out":2,"chroma_noise_intensity":0.09,"composite_preemphasis":0.6,"luma_noise_intensity":0.08,"composite_noise_intensity":0.014,"bandwidth_scale":0.65}},
	{"id":"cctv-mono",
	 "name":"Security camera · monochrome",
	 "group":"Surveillance",
	 "description":"Grainy black-and-white surveillance with hard electronic edges and reduced detail. A stable live feed, without VHS tracking damage.",
	 "route":"Monochrome analog feed · no CRT",
	 "grain":0.28,
	 "saturation":0.0,
	 "lift":0.025,
	 "signal":{"chroma_noise":false,"chroma_phase_noise_intensity":0.0,"composite_noise":false,"luma_smear":0.1,"luma_noise_intensity":0.09,"bandwidth_scale":0.75,"composite_preemphasis":0.45}},
	{"id":"cctv-ir",
	 "name":"Security camera · IR-style night",
	 "group":"Surveillance",
	 "description":"A noisy monochrome night camera with lifted shadows and heavy gain texture. Uses existing scene lighting; it does not add an infrared lamp.",
	 "route":"Night-camera color treatment · no CRT",
	 "grain":0.5,
	 "saturation":0.0,
	 "lift":0.065,
	 "signal":{"chroma_noise":false,"chroma_phase_noise_intensity":0.0,"composite_noise":false,"luma_smear":0.16,"luma_noise_intensity":0.24,"composite_preemphasis":0.05,"bandwidth_scale":0.9}},
	{"id":"broadcast-monitor",
	 "name":"Broadcast preview monitor",
	 "group":"CRT playback",
	 "description":"A well-adjusted studio screen: tight phosphor structure, precise scanlines and very little glow. A clean signal makes the tube easy to judge.",
	 "route":"Clean input → Aperture CRT",
	 "tape":0,
	 "grain":0.0,
	 "crt":1,
	 "knobs":{"MASK_STRENGTH":0.14,"GLOW_HALATION":0.035,"GLOW_DIFFUSION":0.02,"SCANLINE_SIZE_MIN":1.15,"GAMMA_OUTPUT":2.8,"BRIGHTNESS":1.7}},
	{"id":"living-room",
	 "name":"VHS on the living-room TV",
	 "group":"CRT playback",
	 "description":"Warm home video on a good television: gentle tape texture, a fine slot mask and soft phosphor glow. The comfortable nostalgic option.",
	 "route":"VHS SP → Royale CRT",
	 "vhs":true,
	 "grain":0.12,
	 "temperature":0.2,
	 "crt":6,
	 "knobs":{"lcd_gamma":2.8,"crt_gamma":2.35,"beam_min_sigma":0.15,"beam_max_sigma":0.32,"mask_type":1,"mask_triad_size_desired":2.0,"diffusion_weight":0.05,"halation_weight":0.01,"geom_mode_runtime":1,"geom_radius":4.0,"border_size":0.008},
	 "saturation":1.06,
	 "signal":{"composite_noise_intensity":0.025,"chroma_noise_intensity":0.055,"luma_noise_intensity":0.007,"vhs_edge_wave":0.15,"head_switching_height":6}},
	{"id":"kitchen-tv",
	 "name":"Kitchen TV · weak reception",
	 "group":"CRT playback",
	 "description":"A portable TV with a poor aerial: continuous static, restless color and short bursts of interference over a soft dot-mask screen.",
	 "route":"Noisy reception → EasyMode CRT",
	 "grain":0.18,
	 "temperature":0.2,
	 "saturation":0.8,
	 "crt":2,
	 "knobs":{"MASK_STRENGTH":0.16,"SCANLINE_STRENGTH":0.35,"SCANLINE_BRIGHT_MIN":0.5,"SCANLINE_BRIGHT_MAX":0.8,"GAMMA_INPUT":2.1,"GAMMA_OUTPUT":2.25,"BRIGHT_BOOST":1.12,"DILATION":0.3},
	 "fault_rate":6.0,
	 "fault_strength":0.28,
	 "fault_kind":3,
	 "signal":{"composite_noise_intensity":0.19,"luma_noise_intensity":0.055,"chroma_noise_intensity":0.14,"snow_intensity":0.05,"chroma_phase_noise_intensity":0.009}},
	{"id":"motel-tv",
	 "name":"Motel VCR television",
	 "group":"CRT playback",
	 "description":"A worn rental tape on a tired TV: uneven edges, tracking breaks, unfocused highlights and a gently bowed picture.",
	 "route":"VHS copy → Glow Gaussian CRT",
	 "vhs":true,
	 "grain":0.22,
	 "saturation":0.78,
	 "lift":0.028,
	 "crt":3,
	 "signal":{"luma_smear":0.18,"vhs_edge_wave":0.85,"chroma_delay_horizontal":0.65,"composite_noise_intensity":0.1,"luma_noise_intensity":0.04,"chroma_noise_intensity":0.18,"vhs_chroma_loss":0.0005,"tracking_noise":true,"tracking_noise_height":12,"tracking_noise_noise_intensity":0.16,"tracking_noise_wave_intensity":8.0,"tracking_noise_snow_intensity":0.008},
	 "knobs":{"INPUT_GAMMA":2.2,"OUTPUT_GAMMA":2.5,"BOOST":1.12,"BLOOM_STRENGTH":0.16,"GLOW_WHITEPOINT":0.95,"CURVATURE":1,"warpX":0.014,"warpY":0.018,"noise_amt":0.0,"shadowMask":0},
	 "fault_rate":4.0,
	 "fault_strength":0.5,
	 "fault_kind":0},
	{"id":"av-cart",
	 "name":"School AV-cart television",
	 "group":"CRT playback",
	 "description":"A classroom tape copied more than once: pale color, broad color trails and electronic hiss on a brighter CRT. Softer than the living-room TV.",
	 "route":"VHS SP → Glow Lanczos CRT",
	 "vhs":true,
	 "grain":0.2,
	 "saturation":0.8,
	 "crt":4,
	 "knobs":{"INPUT_GAMMA":2.2,"OUTPUT_GAMMA":2.5,"BOOST":1.06,"BLOOM_STRENGTH":0.09,"GLOW_WHITEPOINT":1.0,"CURVATURE":1,"warpX":0.009,"warpY":0.012,"noise_amt":0.0,"shadowMask":1,"maskDark":0.85,"maskLight":1.15},
	 "temperature":0.1,
	 "signal":{"vhs_tape_speed":2,"composite_noise_intensity":0.045,"luma_noise_intensity":0.03,"chroma_noise_intensity":0.15,"chroma_delay_horizontal":2.8,"bandwidth_scale":0.8,"luma_smear":0.32}},
	{"id":"viewfinder",
	 "name":"Camcorder CRT viewfinder",
	 "group":"CRT playback",
	 "description":"A small monochrome electronic viewfinder: sharp luminous edges and a fine raster. No colored phosphor grille or exaggerated curved border.",
	 "route":"Monochrome camera → Hyllian CRT",
	 "tape":0,
	 "grain":0.2,
	 "saturation":0.0,
	 "lift":0.003,
	 "crt":5,
	 "signal":{"chroma_noise":false,"chroma_phase_noise_intensity":0.0,"composite_noise":false},
	 "knobs":{"LUT_selector_param":0,"H_InputGamma":2.4,"H_OUTPUT_GAMMA":1.65,"BRIGHTBOOST":0.9,"SCANLINES_STRENGTH":0.3,"BEAM_MIN_WIDTH":0.85,"BEAM_MAX_WIDTH":1.0,"MASK_STRENGTH":0.0,"GLOW_ENABLE":0,"GLOW_STRENGTH":0.0,"h_curvature":0}},
	{"id":"security-desk",
	 "name":"Security-desk CRT monitor",
	 "group":"CRT playback",
	 "description":"A low-detail monochrome surveillance feed on a CRT: visible raster, moving electronic noise and a trace of phosphor persistence.",
	 "route":"Monochrome camera → Crtsim CRT",
	 "tape":1,
	 "grain":0.22,
	 "saturation":0.0,
	 "lift":0.03,
	 "crt":7,
	 # Crtsim multiplies persistence by 10: stay below .1 so trails decay.
	 "knobs":{"NTSCLerp":0.0,"animate_artifacts":0.0,"Tuning_Satur":0.0,"Tuning_Sharp":0.45,"Tuning_Persistence_R":0.075,"Tuning_Persistence_G":0.075,"Tuning_Persistence_B":0.075,"Tuning_Mask_Opacity":0.0,"mask_toggle":0.0,"BloomScalar":0.04,"Tuning_Overscan":1.0,"Tuning_Barrel":0.04},
	 "signal":{"composite_noise":false,"chroma_noise":false,"chroma_phase_noise_intensity":0.0,"luma_noise_intensity":0.055,"bandwidth_scale":0.75,"use_field":1}},
]

static func make_profile(index: int) -> NtscrtProfile:
	assert(index>=0 and index<LOOKS.size())
	var recipe: Dictionary = LOOKS[index]
	var profile := PROFILE.new()
	profile.tape = int(recipe.get("tape",1))
	profile.tape_damage = 0.5 if profile.tape!=0 else 0.0
	profile.film_grain = float(recipe.get("grain",0.0))
	profile.ambient_fault_rate = float(recipe.get("fault_rate",0.0))
	profile.ambient_fault_strength = float(recipe.get("fault_strength",0.5))
	profile.ambient_fault_kind = int(recipe.get("fault_kind",2))
	profile.color_saturation = float(recipe.get("saturation",1.0))
	profile.color_temperature = float(recipe.get("temperature",0.0))
	profile.color_shadow_lift = float(recipe.get("lift",0.0))
	profile.crt_model = int(recipe.get("crt",0))
	profile.crt_enabled = profile.crt_model>0
	var signal_values := CAMERA.duplicate(true)
	if recipe.get("vhs",false): signal_values.merge(VHS,true)
	signal_values.merge(recipe.get("signal",{}),true)
	profile.ntsc_overrides = signal_values
	if profile.crt_enabled:
		profile.crt_parameters = {profile.selected_crt_model():recipe.get("knobs",{})}
	# Resolve all inactive models as well: captured presets are complete snapshots.
	profile = IO.decode(IO.encode(profile,recipe.name)).profile
	profile.resource_name = recipe.name
	return profile

static func matching_index(profile: NtscrtProfile) -> int:
	var settings: Dictionary = IO.encode(profile).settings
	for index in LOOKS.size():
		var candidate: Dictionary = IO.encode(make_profile(index)).settings
		for key: String in ["quality","reduced_flashing","auto_world_resolution"]:
			candidate[key] = settings[key]
		if candidate==settings: return index
	return -1
